cache:
  node:
    fields:
      - name
  async: thread

# Knowledge base directory, place knowledge base files in this directory, such as various .pdf, .word files
Knowledge-base-path: ./knowledge-base

model:
  graph-entity:
    # Search key for entity retrieval in knowledge graph, i.e., match the value corresponding to this key, usually "name"
    search-key: name
  # Encoding model configuration, only needed when using knowledge base functionality
  embedding:
    # ModelScope model path for text vectorization when building knowledge base, default installation path on Windows is as follows, setting to other paths will download to this path
    model-path: model_download
    # ModelScope model name and version, can be viewed on ModelScope official website, will be downloaded automatically, note the slash direction "/"
    model-name: iic/nlp_corom_sentence-embedding_chinese-base-medical
    model-version: v1.1.0
    device: cpu

# Knowledge graph configuration. Only needed when using knowledge graph functionality
database:
  neo4j:
    url: bolt://localhost:7687
    database: neo4j
    username: neo4j
    # Note: numbers should be in quotes
    password:
    # Define your database's node labels and relationship types for retrieval
    node-label:
      [
        "Primary Department",
        "Secondary Department",
        "Other",
        "Examination Method",
        "Treatment Plan",
        "Manufacturer",
        "Disease",
        "Symptom",
        "Drug",
        "Food",
        "Recipe",
      ]
    relationship-type:
      [
        "Highly Rated Drug",
        "Recommended Food",
        "Belongs To",
        "Common Drug",
        "Complication",
        "Avoided Food",
        "Department",
        "Recommended Recipe",
        "Treatment Method",
        "Produces Drug",
        "Symptom",
        "Diagnostic Suggestion",
      ]
